
# About the project

*Write a short description about the course and add a link to your GitHub repository here. This is an R Markdown (.Rmd) file so you should use R Markdown syntax.*

My GitHib repository: https://github.com/kastematonen/IODS-project

My course diary: https://kastematonen.github.io/IODS-project/


## Assignment 1

#### 1. Check that you have everything installed and created according to the instructions. You should have a GitHub repository, a course diary web page (also on GitHub, in a different address) and the IODS-project started on RStudio using the course templates.

Should be all good. 


#### 2. Just write some of your thoughts about this course freely in the file, e.g., How are you feeling right now? What do you expect to learn? Where did you hear about the course?

I am feeling a bit overwhelmed with the number of files and instructions and books on the course. Not yet sure what to look at when doing something, or what to write down where when reading instructions and excercises. 

I expect to learn a few more things on some basic statistical analyses and I just came accross the course when looking at the course selection in SISU. 

#### Also reflect on your learning experiences with the R for Health Data Science book and the Exercise Set 1: How did it work as a "crash course" on modern R tools and using RStudio? Which were your favorite topics? Which topics were most difficult? Some other comments on the book and our new approach of getting started with R Markdown etc.? (All this is just "warmup" to get well started and learn also the technical steps needed each week in Moodle, that is, submit and review. We will start more serious work next week! You can already look at the next topic in Moodle and begin working with the Exercise Set 2...)

I've worked with Rmd and quarto documents before, so R markdown is at least somewhat familiar to me. The same goes with using git for version control, though I'm used t using it from the command line, so I've never used it from rstudio before. 

About the excercise set, I read it though quickly and the contents all seemed familiar which was nice. 

#### You can immediately start to learn the basics of the R Markdown syntax that we will use for writing the exercise reports: Try, for example, highlighting parts of your text, adding some headers, lists, links etc. Hint: Use the R Markdown Reference Guide or cheatsheet (both found from the RStudio Help). This is an excellent quick (1 min) tour of R Markdown, please watch it: https://rmarkdown.rstudio.com/lesson-1.html

A few tries:

* this is a list
* second element

*text in italics* and **text in bold**

#### 3. Open the index.Rmd file with RStudio. At the beginning of the file, in the YAML options below the 'title' option, add the following option: author: "Your Name". Save the file and "knit" the document (there's a button for that) as an HTML page. This will also update the index.html file.

Added this, my name is visible on the knitted index document. 

#### 4. To make the connection between RStudio and GitHub as smooth as possible, you should create a Personal Access Token (PAT).

Got an error from the command gitcreds::gitcreds_set() saying that it cannot find git. I have been using git on this compute before, so it should be there. Tried reinstalling the latest version (the one i had wasn't the newest one) and the command gitcreds::gitcreds_set() again but got the same message. 

Pushing local changes was not successfull with the way described in the course instructions, but I did manage to do it by using the push button from the git window in rstudio, where it asked for me to sign in to github (which i did with the newly create access token). When pushing changes the next time, it did not ask me to sign in again, so I guess adding the PAT this way is pretty much the same as adding it the way described in the instructions. 

I guess this section wasn't a complite success but using git still works with this ever so slightly different way, so i'd still consider this to be what was needed. I am used to using git from the command line, so i dont think it matters where you operate it, as long as it works.

#### 5. Upload the changes to GitHub (the version control platform) from RStudio

This worked in the way described above. 

#### 6. After a few moments, go to your GitHub repository at https://github.com/your_github_username/IODS-project to see what has changed (please be patient and refresh the page). Also visit your course diary that has been automatically been updated at https://your_github_username.github.io/IODS-project and make sure you see the changes there as well.

Everything looked good, pushing my changes to github worked for i can see my additions to my course diary on the github page. I need to remember to save all the documents and to knit the index file before pushing changes to be sure that all the changes are actually pushed (now the latest addition of one sentence is not visible on the page).
